name: changer_color
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^6.0.3
  flutter_neumorphic: ^3.2.0
  loading_animation_widget: ^1.2.0+4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true

  assets:
    - assets/l10n/